src/Entity/Pvce.php
<?php

namespace App\Entity;

use App\Service\UploaderHelper;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PvceRepository")
 */
class Pvce
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="datetime")
     */
    private $publishedAt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pdfFilename;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->publishedAt;
    }

    public function setPublishedAt(\DateTimeInterface $publishedAt): self
    {
        $this->publishedAt = $publishedAt;

        return $this;
    }

    public function getPdfFilename(): ?string
    {
        return $this->pdfFilename;
    }

    public function setPdfFilename(string $pdfFilename): self
    {
        $this->pdfFilename = $pdfFilename;

        return $this;
    }
    public function getPdfPath()
    {
        return UploaderHelper::PVCE_PDF.'/'.$this->getPdfFilename();
    }
}

src/Entity/Ticket.php
<?php

namespace App\Entity;

use App\Service\UploaderHelper;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TicketRepository")
 */
class Ticket
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="float")
     */
    private $priceCE;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\LigneRequest", mappedBy="ticket", cascade={"persist", "remove"})
     */
    private $ligneRequest;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getPriceCE(): ?float
    {
        return $this->priceCE;
    }

    public function setPriceCE(float $priceCE): self
    {
        $this->priceCE = $priceCE;

        return $this;
    }

    public function getLigneRequest(): ?LigneRequest
    {
        return $this->ligneRequest;
    }

    public function setLigneRequest(?LigneRequest $ligneRequest): self
    {
        $this->ligneRequest = $ligneRequest;

        // set (or unset) the owning side of the relation if necessary
        $newTicket = $ligneRequest === null ? null : $this;
        if ($newTicket !== $ligneRequest->getTicket()) {
            $ligneRequest->setTicket($newTicket);
        }

        return $this;
    }
    public function getImagePath()
    {
        return UploaderHelper::TICKET_IMAGE.'/'.$this->getImage();
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(?string $url): self
    {
        $this->url = $url;

        return $this;
    }
}

src/Controller/ComiteController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Entity\Pvce;
use App\Form\ContactFormType;
use App\Repository\ArticleRepository;
use App\Repository\PartnerRepository;
use App\Repository\PvceRepository;
use App\Repository\TicketRepository;
use App\Repository\ToolRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Serializer\SerializerInterface;

/**
 * Class ComiteController
 * @package App\Controller
 * @IsGranted("ROLE_USER")
 */
class ComiteController extends AbstractController
{
    /**
     * @Route("/", name="app_homepage")
     */
    public function index(ArticleRepository $articleRepos,PvceRepository $pvceRepository)
    {
        $pvce=$pvceRepository->findOneBy([], ['id' => 'desc']);
        $articles=$articleRepos->findIsPublish();
        return $this->render('comite/index.html.twig', [
            'articles' => $articles,
            'pvce' => $pvce
        ]);
    }

    /**
     * @Route("/articles/{slug}",name="app_articles")
     */
    public function show(Article $article)
    {
        return $this->render('comite/show.html.twig', [
                'article' => $article,]);
    }
    /**
     * @Route("/billetterie",name="app_billetterie")
     */
    public function Ticket(TicketRepository $repository)
    {
        $tickets= $repository->findAll();
        return $this->render('comite/ticket.html.twig', [
            'title' => 'Billetterie Battants',
            'tickets'=> $tickets ,]);
    }

    /**
     * @Route("/PvCSE/{id}",name="app_PvCSE")
     */
    public function PvCE(Pvce $pvce,PvceRepository $pvceRepository)
    {

        $pvces=$pvceRepository->findAll();
        return $this->render('comite/PvCSE.html.twig', [
            'pvce'=> $pvce,
            'pvces'=>$pvces,
        ]);
    }
    /**
     * @Route("/partenaires",name="app_partenaire")
     */
    public function partenaire (PartnerRepository $repository)

    {
        $partners=$repository->findAll();
        return $this->render('comite/partner.html.twig', [
            'title' => 'Nos Partenaires',
            'partners'=> $partners,
        ]);
    }
    /**
     * @Route("/outillage",name="app_tool")
     */
    public function tool (ToolRepository $repository)
    {
        $tools=$repository->findAll();
        return $this->render('comite/tool.html.twig', [
            'title'=> 'Location de Materiel',
            'tools' => $tools
        ]);
    }
    /**
     * @Route("/contact", name="app_contact")
     */
    public function contact(Request $request,\Swift_Mailer $swift_Mailer)
    {


        $form = $this->createForm(ContactFormType::class);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $formMessage=$form->getData();


                $message = (new \Swift_Message('Confirmation de Commande'))
                    ->SetFrom($formMessage["emailContact"])
                    ->setTo('m.ch5500@gmail.com')
                    ->setBody($this->renderView('comite/emailContact.html.twig',
                        ['message' => $formMessage['messageContact'],
                            'nom'=>$formMessage['nameContact'],
                            'email'=>$formMessage['emailContact']
                        ]), 'text/html');
                $swift_Mailer->send($message);



            $this->addFlash('success', 'Votre message a bien été envoyé');
            return $this->redirectToRoute('app_homepage',[

            ]);
        }

        return $this->render('comite/contact.html.twig', [
            'contactForm' => $form->createView(),
            'title'=>'Contact'

        ]);
    }

}

templates/comite/PvCSE.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{ pvce.title }}{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('pvce') }}
{% endblock %}

{% block body %}

<div class="container">
    <div class="site__title text-center">
        <h1>{{ pvce.title }}</h1>
    </div>
    <div class="row">
            <div class="col-sm-8">
               <div id="app">
  <div id="toolbar">
    <div id="pager">
     <button data-pager="prev">prev</button>
     <button data-pager="next">next</button>
    </div>
    <div id="page-mode">
     <label>Page Mode <input type="number" value="1" min="1"></label>
    </div>
  </div>
  <div id="viewport" role="main"></div>

</div>
            </div>
    <div class="col-sm-4 site__references">
                <div class="site__references__title text-center">
            <h3>PV de CSE</h3>

                </div>
        <div class="site__references__lien">
        {% for pv in pvces %}
            <a href="{{ path('app_PvCSE', {
                id: pv.id
            }) }}">
                {{ pv.title}}
            </a><br><br>
        {%  endfor %}
    </div>

    </div></div>

{% endblock %}
            {% block javascripts %}
    {{ parent() }}
    <script src="https://unpkg.com/pdfjs-dist@latest/build/pdf.min.js"></script>
                {{ encore_entry_script_tags('pvce') }}
<script>
  window.onload = () => {
    {#initPDFViewer("{{ asset('uploads/pvce_Pdf/P.V. DE LA REUNION DU C.E. décembre 2018.pdf')}}")#}
      initPDFViewer("{{uploaded_asset(pvce.pdfPath)}}")
  }
</script>
{% endblock %}

templates/comite/contact.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{ title }}{% endblock %}

{% block body %}

    <div class="container">
        <div class="row justify-content-center site__title">
            <h1>Contactez Nous !!!</h1>
        </div>

        <div class="row tool__table">


                {{ form_start(contactForm) }}

               {{ form_row(contactForm.nameContact) }}
                {{ form_row(contactForm.emailContact) }}
                {{ form_row(contactForm.messageContact) }}



            <button type="submit" class="btn btn-primary">Envoyer</button>
            {{ form_end(contactForm) }}

        </div>
    </div>

{% endblock %}

templates/comite/header.html.twig
<div class="header">

    <a class="logo left" href="/">
        <img src="{{ asset('build/images/logo.png') }}") alt="CE Battants">

    </a>


    {% block header_navigation %}




                {% block navigation %}
                    {{ include('comite/navigation.html.twig') }}
                {% endblock %}


    {% endblock %}


</div>

templates/comite/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}HOMEPAGE!{% endblock %}
{% block header %}
    {{ include('comite/header.html.twig') }}

{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-lg-10 recduction-img">

            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    {% for article in articles %}
                    <li data-target="#carouselExampleIndicators" data-slide-to="{{ loop.index }}" {% if loop.first %}class="active"{% endif %}></li>
                    {% endfor %}
                </ol>
                <div class="carousel-inner">

                    {% for article in articles %}
                    <div class="carousel-item {% if loop.first %}active{% endif %}">
                        <a href="{{ path('app_articles', {'slug': article.slug} )}}" ><img class="d-block w-100" src="{{ uploaded_asset(article.imagePath) }}" alt="Second slide"></a>
                        <div class="carousel-caption d-none d-md-block">
                            <h1>{{article.title}}</h1>

                        </div>
                    </div>
                    {% endfor %}
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>



            </div>
            <div class="col-lg-2 recduction-img"><a href="{{ path('app_partenaire') }}"><img class="img-fluid" src="{{ asset('build/images/ten-percent-off.png') }}"></a>
            <a href="{{ path('app_partenaire') }}"><img class="img-fluid" src="{{ asset('build/images/team.png') }}"></a>
            <a href="{{ path('app_tool') }}"><img class="img-fluid" src="{{ asset('build/images/tool.png') }}"></a></div>
        </div>


        <div class="row">
              <div class="col-lg-4 homepage-img_bas"><a href="{{ path('app_billetterie') }}"><img class="img-thumbnail" src="{{ asset('build/images/tickets.jpg') }}"></a> <div class="carousel-caption d-none d-md-block">
                    <h1>Billetterie</h1>

                </div></div>


            <div class="col-lg-4 homepage-img_bas"><a href="{{ path('app_PvCSE', {
                    id: pvce.id
                }) }}"><img class="img-thumbnail" src="{{ asset('build/images/pen.jpg') }}"></a><div class="carousel-caption d-none d-md-block">
                    <h1>PV de CE</h1>

                </div></div>
            <div class="col-lg-4 homepage-img_bas"><a href="{{ path('app_contact') }}"><img class="img-thumbnail" src="{{ asset('build/images/e-mail.jpg') }}"></a><div class="carousel-caption d-none d-md-block">
                    <h1>Nous contacter</h1>

                </div></div>
        </div>



    </div>

{% endblock %}

templates/comite/navigation.html.twig
{% block stylesheets %}

    {{ encore_entry_link_tags('app') }}
    {{ encore_entry_link_tags('nav') }}
    {{ encore_entry_link_tags('bouton') }}
{% endblock %}



<div class="toggle_btn">
    <span></span>
    <span></span>
    <span></span>
    <span></span>
</div>

<nav class="menu">
    <div class="row">
    <div class="menu__text col-md-6">
        <a href="{{ path('app_homepage') }}">Accueil</a>
        <a href="{{ path('app_tool') }}">Matériel</a>
        <a href="{{ path('app_logout') }}">Se Déconnecter</a>

        {% if is_granted('ROLE_ADMIN_ARTICLE') %}
            <a  href="{{ path('admin_article_new') }}">Admin</a>
        {% endif %}

    </div>
        <div class="contact col-md-6">
                <div class="contact__text">
            <h1>Peut-on vous aider?</h1>
             <p>CSE Essilor BAttants<br>
                Bureau 113,<br>
                 Ligny en Barrois</p>
            <h2>Tél:06-01-02-03-04</h2>
                </div>
{#                <div class="col-md-12">#}
{#                    <button type="button" class="btn btn-link"><i class="fab fa-twitter fa-2x"></i></button>&nbsp;&nbsp;<button type="button" class="btn btn-link"><i class="fab fa-instagram fa-2x"></i></button>&nbsp;&nbsp;<button type="button" class="btn btn-link"><i class="fab fa-facebook-f fa-2x"></i></button>#}
{#                </div>#}
            <div class="buttons">
            <a href="{{ path('app_contact') }}">

                <button class="blob-btn-yellow">
                   Contactez Nous
                    <span class="blob-btn__inner">
      <span class="blob-btn-yellow__blobs">
        <span class="blob-btn-yellow__blob"></span>
        <span class="blob-btn-yellow__blob"></span>
        <span class="blob-btn-yellow__blob"></span>
        <span class="blob-btn-yellow__blob"></span>
      </span>
                    </span></button>


            </a>

        </div>



        </div>
    </div>

</nav>

{% block javascripts %}

    {{ encore_entry_script_tags('nav') }}


{% endblock %}

templates/comite/partenaire.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{ title }}{% endblock %}

{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <img class="img-fluid" src="{{ asset('build/images/fairground.jpg') }}"></div>
            <div class="col-md-6">
            <h1>{{ title }}</h1>
            </div>


{% endblock %}

templates/comite/partner.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{ title }}{% endblock %}

{% block body %}

    <div class="container">
        <div class="row justify-content-center site__title">
            <h1>{{ title|upper }}</h1>
        </div>
        <div class="partner__container">
            <div class="row partner__offer__row ">


                {% for partner in partners  %}



                <div class="col-md-4 partner__offer__container" style="flex-grow: 1;">
                    <div class="partner__offer">

                        <img class="img-fluid" src="{{uploaded_asset(partner.imagePath)}}">
                        <div class="partner__offer__details">
                            <div class="partner__offer__title" > <strong>{{ partner.name }}</strong> </div>
                            <span class="partner__offer__trait"></span></div>
                        <div class="partner__offer__triangle"></div>
                    </div>
                    <div class="partner__offer__spacer"></div>
                    <div id="partner__offer__card" class="partner__offer__card">
                        <div class="partner__cardBox">
                            <h4  class="partner_cardBox__name">{{ partner.name|upper }}<span class="partner__cardBox__trait"></span></h4>
                            <div class="partner__cardBox__prize"><span>Type de réduction: {{ partner.typeReduction }}€</span></div>
                            <div class="partner__cardBox__description">{{ partner.description|raw }}</div>
                            <a class="partner__cardBox__close"><span>X</span></a>
                            <div class="partner__cardBox__redirection"><a href="{{ partner.url }}">Voir le site <i class="fa fa-chevron-circle-right fa-1x"></i> </a> </div>
                                                    </div>
                    </div></div>

                {% if loop.index % 3 == 0 %}
            </div><div class="row partner__offer__row ">

                {% endif %}

                {% endfor %}

            </div>
        </div>
    </div>

{% endblock %}
{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('partner') }}
{% endblock %}

templates/comite/show.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{ article.title }}{% endblock %}

{% block body %}

    <div class="container">
        <div class="site__title text-center">
        <h1>{{ article.title|upper}}</h1>
        </div>
        <div class="row show__body">
            <div class="col-sm-8">
                <img class="img-fluid show__img" src="{{uploaded_asset(article.imagePath)}}"><br>
                <p>{{ article.content|raw }}</p>

            </div>
            <div class="col-sm-4 show__references">
                <div class="show__references__title text-center">
            <h3>Documents Téléchargeables</h3>
                </div>
                <ul class="list-group small show__references__download">
                    {% for reference in article.articleReferences %}
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            {{ reference.originalFilename }}
                            <span>
                            <a href="{{ path('admin_article_download_reference', {
                                id: reference.id
                            }) }}"><span class="fa fa-download"></span></a>
                        </span>
                        </li>
                    {% endfor %}
                </ul>

            </div>

<div>

</div>
    </div></div>
{% endblock %}

templates/comite/ticket.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{ title }}{% endblock %}

{% block body %}

    <div class="container">
    <div class="row justify-content-center site__title">
        <h1>{{ title|upper }}</h1>
    </div>
<div class="ticket__container">
        <div class="row ticket__offer__row ">


          {% for ticket in tickets  %}



            <div class="col-md-4 ticket__offer__container" style="flex-grow: 1;">
            <div class="ticket__offer">

                <img class="img-fluid" src="{{uploaded_asset(ticket.imagePath)}}">
                <div class="ticket__offer__details">
                    <div class="ticket__offer__title" > <strong>{{ ticket.title }}</strong> </div>
                    <span class="ticket__offer__trait"></span></div>
                <div class="ticket__offer__triangle"></div>
            </div>
                <div class="ticket__offer__spacer"></div>
                <div id="ticket__offer__card" class="ticket__offer__card">
                    <div class="ticket__cardBox">
                    <h4  class="ticket_cardBox__name">{{ ticket.title|upper }}<span class="ticket__cardBox__trait"></span></h4>
                    <div class="ticket__cardBox__prize"><span>Tarif : {{ ticket.priceCE }}€</span></div>
                    <div class="ticket__cardBox__description">{{ ticket.description|raw }}</div>
                    <a class="ticket__cardBox__close"><span>X</span></a>
                     <div class="ticket__cardBox__redirection"><a href="{{ticket.url}}">Voir le site <i class="fa fa-chevron-circle-right fa-1x"></i> </a> </div>
                    <div class="ticket__cardBox__button">
                    <a href="#"class="btn btn-success float-right"><i class="fa fa-shopping-cart mr-1"></i>Ajouter </a>
                    </div>
                    </div>
            </div></div>

            {% if loop.index % 3 == 0 %}
        </div><div class="row ticket__offer__row ">

    {% endif %}

            {% endfor %}

        </div>
        </div>
        </div>

{% endblock %}
{% block javascripts %}
    {{ parent() }}
        {{ encore_entry_script_tags('ticket') }}
    {% endblock %}

templates/comite/tool.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{ title }}{% endblock %}

{% block body %}

    <div class="container">
        <div class="row justify-content-center site__title">
            <h1>{{ title|upper }}</h1>
        </div>

        <div class="row tool__table">
            <table class="table table-striped">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">Articles</th>
                    <th scope="col">Tarifs/Semaine</th>
                </tr>
                </thead>
                <tbody>
            {% for tool in tools  %}

                <tr>
                    <th scope="row">{{ tool.name|upper }}</th>
                    <td>{{ tool.price }}€</td>
                </tr>
            {% endfor %}
                </tbody>
            </table>

        </div>
    </div>

{% endblock %}